import React from 'react';
import { useLocale } from '../contexts/LocaleContext';

const TermsOfService: React.FC = () => {
  const { t, locale } = useLocale();
  return (
    <div className="space-y-4 text-text-primary">
      <h1 className="text-3xl font-bold text-accent mb-4">{t('terms')}</h1>
      {locale !== 'en' && <p className="p-3 bg-amber-900/50 border border-amber-700 text-amber-300 text-sm rounded-lg italic">{t('legalDisclaimer')}</p>}
      <p>Last updated: {new Date().toLocaleDateString()}</p>

      <h2 className="text-xl font-semibold text-accent pt-4">1. Acceptance of Terms</h2>
      <p>
        By accessing or using the AI Letter Generator application ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service.
      </p>

      <h2 className="text-xl font-semibold text-accent pt-4">2. Description of Service</h2>
      <p>
        The Service is an AI-powered tool designed to assist users in generating professional letters, such as cover letters and university admission letters. The content is generated by a large language model and should be reviewed for accuracy and suitability before use.
      </p>

      <h2 className="text-xl font-semibold text-accent pt-4">3. User Responsibilities</h2>
      <p>
        You are solely responsible for the information you provide to the Service and for the use of the generated content. You agree not to use the Service for any unlawful purpose. You must review and edit any generated letter to ensure it accurately represents you and is appropriate for its intended purpose.
      </p>

      <h2 className="text-xl font-semibold text-accent pt-4">4. Disclaimer of Warranties</h2>
      <p>
        The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, that the Service will be uninterrupted, error-free, or that the generated content will be accurate, complete, or suitable for your needs. We are not a career advisory or admissions service.
      </p>

      <h2 className="text-xl font-semibold text-accent pt-4">5. Limitation of Liability</h2>
      <p>
        In no event shall AI Letter Generator, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
      </p>

      <h2 className="text-xl font-semibold text-accent pt-4">6. Changes to Terms</h2>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
      </p>

      <div className="mt-8 pt-6 border-t border-border text-center">
        <a href="/dashboard" className="inline-block px-6 py-2 bg-indigo-600 hover:bg-indigo-500 rounded-md transition-colors font-medium">
            {t('backToGenerator')}
        </a>
      </div>
    </div>
  );
};

export default TermsOfService;
