import React from 'react';

const TermsOfService: React.FC = () => {
  return (
    <section className="bg-slate-800/50 rounded-xl p-6 md:p-8 shadow-2xl border border-slate-700 animate-fade-in">
      <div className="max-w-4xl mx-auto">
        <a href="#" className="text-sm text-indigo-400 hover:text-indigo-300 mb-6 inline-block">&larr; Back to Generator</a>
        <h2 className="text-3xl font-bold text-cyan-300 mb-6 border-b border-slate-700 pb-3">Terms of Service</h2>
        
        <div className="space-y-4 text-slate-300 prose prose-invert max-w-none">
            <p>Last updated: [Date]</p>

            <h3 className="text-xl font-semibold text-slate-200">1. Acceptance of Terms</h3>
            <p>
                By accessing and using cover-letter-ai-xi ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>

            <h3 className="text-xl font-semibold text-slate-200">2. Description of Service</h3>
            <p>
                The Service is an AI-powered tool designed to assist users in generating professional letters. The output is generated by a large language model and may not always be accurate or complete. You are responsible for reviewing and editing the generated content to ensure it meets your needs.
            </p>

            <h3 className="text-xl font-semibold text-slate-200">3. User Conduct</h3>
            <p>
                You agree not to use the Service to generate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.
            </p>

            <h3 className="text-xl font-semibold text-slate-200">4. Disclaimer of Warranties</h3>
            <p>
                The Service is provided on an "as is" and "as available" basis. cover-letter-ai-xi makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
            </p>

            <h3 className="text-xl font-semibold text-slate-200">5. Limitation of Liability</h3>
            <p>
                In no event shall cover-letter-ai-xi or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on our website, even if we or an authorized representative has been notified orally or in writing of the possibility of such damage.
            </p>

            <h3 className="text-xl font-semibold text-slate-200">6. Changes to Terms</h3>
            <p>
                We reserve the right to modify these terms from time to time at our sole discretion. Therefore, you should review this page periodically. Your continued use of the Website or our service after any such change constitutes your acceptance of the new Terms.
            </p>
        </div>
      </div>
    </section>
  );
};

export default TermsOfService;
